- name: Deploy Waker on Raspi
  hosts: all
  collections:
    - devsec.hardening
  roles:
    - ssh_hardening
    - core
    - mosquitto
    - waker
  vars:
    ssh_pam_support: false
    ssh_use_pam: false
    ssh_kerberos_support: false
    ssh_server_password_login: false
    sshd_authenticationmethods: publickey
