name: Deploy Waker using Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: cocopaps/ansible-ci:latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy with Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.6.1
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          ANSIBLE_FORCE_COLOR: 'true'
          ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
          MOSQUITTO_USER: ${{secrets.MOSQUITTO_USER}}
          MOSQUITTO_PASSWORD: ${{secrets.MOSQUITTO_PASSWORD}}
          WAKER_PC_MAC_ADDR: ${{secrets.WAKER_PC_MAC_ADDR}}
        with:
          playbook: playbook.yml
          directory: ./
          key: ${{secrets.SSH_PRIVATE_KEY}}
          known_hosts: .known_hosts
          requirements: requirements.yml
          options: |
            --inventory inventory.yml
            --verbose
